# Generated by Django 4.1 on 2022-08-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
